version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: '10g'
